### ISSUE TITLE
Number of evaluations in examples main loop

### ISSUE THREAD

**Issue by montanier** [AlexanderFabisch/CMA-ESpp#1]
Hello,

The loop doing the evaluation part at the line 63 of example1.cpp will always look at 13 individuals. It gets the Lamda value of the GetScalar enum. This loop should work on the lambda value of the parameters.

A similar problem happens at the line 134 of example2.cpp.

Regards
Jean-Marc

**Comment by AlexanderFabisch** [comment]
Hi,

I don't see any error here. If I set parameters.lambda = 20, evo.get(CMAES<double>::Lambda) will return 20.

**Comment by montanier** [comment]
Sorry, my bad. I should have check better before sending something. Indeed it's all working fine.

Jean-Marc

**Comment by AlexanderFabisch** [comment]
No problem at all. :) You are always welcome to submit pull requests that improve the code or report bugs.
